from pydantic import BaseModel
from typing import List, Optional

# Base schema for creating a new topic
class TopicCreate(BaseModel):
    topic_name: str
    description: Optional[str] = None
    difficulty: Optional[str] = "Beginner"

# Schema for returning a topic (includes the ID generated by the database)
class TopicResponse(TopicCreate):
    topic_id: int

    class Config:
        from_attributes = True
# Schema for creating a dependency
class DependencyCreate(BaseModel):
    parent_topic_id: int
    child_topic_id: int

# Schema for returning a dependency
class DependencyResponse(DependencyCreate):
    id: int

    class Config:
        from_attributes = True
# Schema for requesting a learning path
class PathRequest(BaseModel):
    topic: str